name: Go Linter
on:
  push:
    branches:
      - '**'
jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.29
          only-new-issues: true
